import { IProduct } from "../view/home/interfaces";
import { IHotel, IHotelRoom } from "../interfaces";

export const placeholderProductPage: IProduct[] = [
    {
        title: "Autumn Mantle Hotel & Spa",
        img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
        price: 500000,
        city: "West Jakarta",
        regency: "Grogol",
        rating: 4.6,
        ratingCount: 512,
        description: "This is a description"
    },
    {
        title: "Rose Pinnacle Motel",
        img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
        price: 200000,
        city: "West Jakarta",
        regency: "Grogol",
        rating: 4.6,
        ratingCount: 512,
        description: "This is a description"
    },
    {
        title: "Scarlet Grotto Hotel",
        img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
        price: 200000,
        city: "West Jakarta",
        regency: "Grogol",
        rating: 4.6,
        ratingCount: 512,
        description: "This is a description"
    },
    {
        title: "Cerulean Landscape Resort & Spa",
        img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
        price: 200000,
        city: "West Jakarta",
        regency: "Grogol",
        rating: 4.6,
        ratingCount: 512,
        description: "This is a description"
    },
    {
        title: "Dual Aegis Resort",
        img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
        price: 200000,
        city: "West Jakarta",
        regency: "Grogol",
        rating: 4.6,
        ratingCount: 512,
        description: "This is a description"
    },
    {
        title: "Pleasant Maple Resort",
        img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
        price: 200000,
        city: "West Jakarta",
        regency: "Grogol",
        rating: 4.6,
        ratingCount: 512,
        description: "This is a description"
    },
    {
        title: "Marina Vertex Hotel & Spa",
        img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
        price: 200000,
        city: "West Jakarta",
        regency: "Grogol",
        rating: 4.6,
        ratingCount: 512,
        description: "This is a description"
    },
    {
        title: "Taman Nasional Way Kambas",
        img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
        price: 200000,
        city: "West Jakarta",
        regency: "Grogol",
        rating: 4.6,
        ratingCount: 512,
        description: "This is a description"
    },
    {
        title: "Taman Laut Bunaken",
        img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
        price: 200000,
        city: "West Jakarta",
        regency: "Grogol",
        rating: 4.6,
        ratingCount: 512,
        description: "This is a description"
    },
    {
        title: "Pulau Komodo Tour",
        img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
        price: 200000,
        city: "West Jakarta",
        regency: "Grogol",
        rating: 4.6,
        ratingCount: 512,
        description: "This is a description"
    },
    {
        title: "",
        img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
        price: 200000,
        city: "West Jakarta",
        regency: "Grogol",
        rating: 4.6,
        ratingCount: 512,
        description: "This is a description"
    },
    {
        title: "Jatim Park 2",
        img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
        price: 200000,
        city: "West Jakarta",
        regency: "Grogol",
        rating: 4.6,
        ratingCount: 512,
        description: "This is a description"
    },
    {
        title: "",
        img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
        price: 200000,
        city: "West Jakarta",
        regency: "Grogol",
        rating: 4.6,
        ratingCount: 512,
        description: "This is a description"
    },
    {
        title: "",
        img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
        price: 200000,
        city: "West Jakarta",
        regency: "Grogol",
        rating: 4.6,
        ratingCount: 512,
        description: "This is a description"
    },
    {
        title: "",
        img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
        price: 200000,
        city: "West Jakarta",
        regency: "Grogol",
        rating: 4.6,
        ratingCount: 512,
        description: "This is a description"
    },
    {
        title: "",
        img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
        price: 200000,
        city: "West Jakarta",
        regency: "Grogol",
        rating: 4.6,
        ratingCount: 512,
        description: "This is a description"
    },
    {
        title: "",
        img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
        price: 200000,
        city: "West Jakarta",
        regency: "Grogol",
        rating: 4.6,
        ratingCount: 512,
        description: "This is a description"
    },
    {
        title: "",
        img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
        price: 200000,
        city: "West Jakarta",
        regency: "Grogol",
        rating: 4.6,
        ratingCount: 512,
        description: "This is a description"
    },
];

export const placeholderProductPageTwo: IProduct[] = [
    {
        title: "The Grand Budapest Hotel",
        img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
        price: 200000,
        city: "West Jakarta",
        regency: "Grogol",
        rating: 4.9,
        ratingCount: 21,
        description: "This is a description"
    },
  
    {
        title: "The Grand Budapest Hotel",
        img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
        price: 200000,
        city: "West Jakarta",
        regency: "Grogol",
        rating: 4.9,
        ratingCount: 21,
        description: "This is a description"
    },
  
    {
        title: "The Grand Budapest Hotel",
        img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
        price: 200000,
        city: "West Jakarta",
        regency: "Grogol",
        rating: 4.9,
        ratingCount: 21,
        description: "This is a description"
    },
  
    {
        title: "The Grand Budapest Hotel",
        img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
        price: 200000,
        city: "West Jakarta",
        regency: "Grogol",
        rating: 4.9,
        ratingCount: 21,
        description: "This is a description"
    },
  
    {
        title: "The Grand Budapest Hotel",
        img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
        price: 200000,
        city: "West Jakarta",
        regency: "Grogol",
        rating: 4.9,
        ratingCount: 21,
        description: "This is a description"
    },
  
    {
        title: "The Grand Budapest Hotel",
        img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
        price: 200000,
        city: "West Jakarta",
        regency: "Grogol",
        rating: 4.9,
        ratingCount: 21,
        description: "This is a description"
    },
  
    {
        title: "The Grand Budapest Hotel",
        img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
        price: 200000,
        city: "West Jakarta",
        regency: "Grogol",
        rating: 4.9,
        ratingCount: 21,
        description: "This is a description"
    },
  
    {
        title: "The Grand Budapest Hotel",
        img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
        price: 200000,
        city: "West Jakarta",
        regency: "Grogol",
        rating: 4.9,
        ratingCount: 21,
        description: "This is a description"
    },
  
    {
        title: "The Grand Budapest Hotel",
        img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
        price: 200000,
        city: "West Jakarta",
        regency: "Grogol",
        rating: 4.9,
        ratingCount: 21,
        description: "This is a description"
    },
  
];


// export const hotels: IHotel[] = [
//     {
//         id: 1,
//         title: "Sublime Shield Resort",
//         minPrice: 1500000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.3,
//         ratingCount: 21,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Group",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 2,
//         title: "Summer Majesty Resort",
//         minPrice: 2000000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.6,
//         ratingCount: 53,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Family",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 3,
//         title: "Jade View Hotel",
//         minPrice: 2200000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.7,
//         ratingCount: 39,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Formal",
//         type: "Solo",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 4,
//         title: "Golden Sword Motel",
//         minPrice: 1200000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.0,
//         ratingCount: 127,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Busy",
//         type: "Group",
//         audience: "Local",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 5,
//         title: "Ruby Peaks Hotel",
//         minPrice: 1400000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 3.9,
//         ratingCount: 12,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Busy",
//         type: "Couple",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 6,
//         title: "Historic Grotto Motel",
//         minPrice: 1800000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.2,
//         ratingCount: 68,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Busy",
//         type: "Family",
//         audience: "Local",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 7,
//         title: "Saffron Island Hotel",
//         minPrice: 1950000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.9,
//         ratingCount: 73,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Busy",
//         type: "Couple",
//         audience: "Local",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 8,
//         title: "Sunset Haven Resort",
//         minPrice: 1500000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.6,
//         ratingCount: 6,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Family",
//         audience: "Local",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 9,
//         title: "Winter Gulf Resort",
//         minPrice: 3200000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.4,
//         ratingCount: 24,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Solo",
//         audience: "Local",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 10,
//         title: "Atlantic Gardens Hotel",
//         minPrice: 1500000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.3,
//         ratingCount: 21,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Group",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 11,
//         title: "Sublime Shield Resort",
//         minPrice: 1500000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.3,
//         ratingCount: 21,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Group",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 12,
//         title: "Brass Gardens Hotel",
//         minPrice: 1500000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.3,
//         ratingCount: 21,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Group",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 13,
//         title: "Western Gardens Motel",
//         minPrice: 1500000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.3,
//         ratingCount: 21,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Group",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 14,
//         title: "Parallel Phoenix Resort",
//         minPrice: 1500000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.3,
//         ratingCount: 21,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Group",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 15,
//         title: "Silver Cottage Motel",
//         minPrice: 1500000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.3,
//         ratingCount: 21,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Group",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 16,
//         title: "Obsidian Expanse Hotel & Spa",
//         minPrice: 1500000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.3,
//         ratingCount: 21,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Group",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 17,
//         title: "Emerald Dome Resort",
//         minPrice: 1500000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.3,
//         ratingCount: 21,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Group",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 18,
//         title: "Olive Paradise Resort",
//         minPrice: 1500000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.3,
//         ratingCount: 21,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Group",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 19,
//         title: "Modest Vale Resort & Spa",
//         minPrice: 1500000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.3,
//         ratingCount: 21,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Group",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 20,
//         title: "Jade Summit Resort & Spa",
//         minPrice: 1500000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.3,
//         ratingCount: 21,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Group",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 21,
//         title: "Cerulean Woodland Resort",
//         minPrice: 1500000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.3,
//         ratingCount: 21,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Group",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 22,
//         title: "Triple Canopy Resort",
//         minPrice: 1500000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.3,
//         ratingCount: 21,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Group",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 23,
//         title: "Western Luxury Hotel",
//         minPrice: 1500000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.3,
//         ratingCount: 21,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Group",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 24,
//         title: "Southern Pass Hotel & Spa",
//         minPrice: 1500000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.3,
//         ratingCount: 21,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Group",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 25,
//         title: "Supreme Aegis Hotel",
//         minPrice: 1500000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.3,
//         ratingCount: 21,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Group",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 26,
//         title: "King's Cove Hotel",
//         minPrice: 1500000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.3,
//         ratingCount: 21,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Group",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 27,
//         title: "Peaceful Dream Hotel",
//         minPrice: 1500000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.3,
//         ratingCount: 21,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Group",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 28,
//         title: "Aquamarine Bliss Hotel & Spa",
//         minPrice: 1500000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.3,
//         ratingCount: 21,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Group",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 29,
//         title: "Rose Pinnacle Motel",
//         minPrice: 1500000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.3,
//         ratingCount: 21,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Group",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 30,
//         title: "Soft Hill Hotel",
//         minPrice: 1500000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.3,
//         ratingCount: 21,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Group",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 31,
//         title: "Bronze Carnaval Motel",
//         minPrice: 1500000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.3,
//         ratingCount: 21,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Group",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 32,
//         title: "Tranquil Horizon Hotel",
//         minPrice: 1500000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.3,
//         ratingCount: 21,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Group",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 33,
//         title: "Crimson Residence Hotel",
//         minPrice: 1500000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.3,
//         ratingCount: 21,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Group",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 34,
//         title: "Mellow Mirror Hotel",
//         minPrice: 1500000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.3,
//         ratingCount: 21,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Group",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
//     {
//         id: 35,
//         title: "Emerald Mantle Hotel",
//         minPrice: 1500000,
//         img: "https://i1.wp.com/www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg?ssl=1",
//         city: "Tangerang",
//         address: "Jl Pemuda 10",
//         rating: 4.3,
//         ratingCount: 21,
//         description: "tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse",
//         mood: "Relaxing",
//         type: "Group",
//         audience: "Tourist",
//         roomType: [],
//         facilities: []
//     },
// ]